// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
        //
        // THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

        
            #[path = "rwalker.skel.rs"]
            mod rwalker_skel;
            pub use rwalker_skel::*;
